Imports System
Imports System.Data
Imports System.Data.SqlClient
Imports System.Data.Common
Imports Sit.BusinessEntities
Imports Microsoft.Practices.EnterpriseLibrary.Data
Imports Microsoft.Practices.EnterpriseLibrary.Data.Sql

Public Class ArchivoPlanoDAM


    Private sqlCommand As String = ""
    Private oArchivoPlanoRow As ArchivoPlanoBE.ArchivoPlanoRow

    Public Sub New()

    End Sub

    Public Function Seleccionar(ByVal ArchivoCodigo As String, ByVal dataRequest As DataSet) As DataSet
        Dim db As Database = DatabaseFactory.CreateDatabase()
        Dim sqlCommand As String = "ArchivoPlano_seleccionar"
        Dim dbCommand As dbCommand = db.GetStoredProcCommand(sqlCommand)
        db.AddInParameter(dbCommand, "@ArchivoCodigo", DbType.String, ArchivoCodigo)
        Return db.ExecuteDataSet(dbCommand)

    End Function

    Public Function Listar(Optional ByVal grupoArchivo As String = "") As DataSet
        Dim db As Database = DatabaseFactory.CreateDatabase()
        Dim dbCommand As dbCommand = db.GetStoredProcCommand("ArchivoPlano_Listar")
        db.AddInParameter(dbCommand, "@p_ArchivoGrupo", DbType.String, grupoArchivo)
        Return db.ExecuteDataSet(dbCommand)
    End Function

    Public Function ListarEstructura(ByVal ArchivoCodigo As String, ByVal dataRequest As DataSet) As DataSet
        Dim db As Database = DatabaseFactory.CreateDatabase()
        Dim dbCommand As dbCommand = db.GetStoredProcCommand("ArchivoPlanoEstructura_Listar")
        db.AddInParameter(dbCommand, "@ArchivoCodigo", DbType.String, ArchivoCodigo)
        Return db.ExecuteDataSet(dbCommand)
    End Function

    Public Function ListarResultado(ByVal dataRequest As DataSet) As DataSet
        Dim db As Database = DatabaseFactory.CreateDatabase()
        Dim dbCommand As dbCommand = db.GetStoredProcCommand("ListarResultadoDatatec")

        Return db.ExecuteDataSet(dbCommand)
    End Function

    Public Function Insertar(ByVal ob As ArchivoPlanoBE, ByVal dataRequest As DataSet)
        Dim db As Database = DatabaseFactory.CreateDatabase()
        Dim sqlCommand As String = "ArchivoPlano_Insertar"
        Dim dbCommand As dbCommand = db.GetStoredProcCommand(sqlCommand)
        oArchivoPlanoRow = CType(ob.ArchivoPlano.Rows(0), ArchivoPlanoBE.ArchivoPlanoRow)

        db.AddInParameter(dbCommand, "@ArchivoCodigo", DbType.String, oArchivoPlanoRow.ArchivoCodigo)
        db.AddInParameter(dbCommand, "@ArchivoNombre", DbType.String, oArchivoPlanoRow.ArchivoNombre)
        db.AddInParameter(dbCommand, "@ArchivoDescripcion", DbType.String, oArchivoPlanoRow.ArchivoDescripcion)
        db.AddInParameter(dbCommand, "@ArchivoExtension", DbType.String, oArchivoPlanoRow.ArchivoExtension)
        db.AddInParameter(dbCommand, "@ArchivoUbicacion", DbType.String, oArchivoPlanoRow.ArchivoUbicacion)
        db.AddInParameter(dbCommand, "@ArchivoTipoSeparador", DbType.String, oArchivoPlanoRow.ArchivoTipoSeparador)
        db.AddInParameter(dbCommand, "@ArchivoSeparador", DbType.String, oArchivoPlanoRow.ArchivoSeparador)
        db.AddInParameter(dbCommand, "@ArchivoLongitudRegistro", DbType.String, oArchivoPlanoRow.ArchivoLongitudRegistro)
        db.AddInParameter(dbCommand, "@ArchivoSeparadorDecimales", DbType.String, oArchivoPlanoRow.ArchivoSeparadorDecimales)
        db.AddInParameter(dbCommand, "@UsuarioCreacion", DbType.String, oArchivoPlanoRow.UsuarioCreacion)
        db.AddInParameter(dbCommand, "@FechaCreacion", DbType.Decimal, oArchivoPlanoRow.FechaCreacion)
        db.AddInParameter(dbCommand, "@HoraCreacion", DbType.String, oArchivoPlanoRow.HoraCreacion)

        db.ExecuteNonQuery(dbCommand)

    End Function

    Public Function Modificar(ByVal ob As ArchivoPlanoBE, ByVal dataRequest As DataSet) As Boolean

        Dim db As Database = DatabaseFactory.CreateDatabase()
        Dim dbCommand As dbCommand = db.GetStoredProcCommand("ArchivoPlano_Modificar")
        oArchivoPlanoRow = CType(ob.ArchivoPlano.Rows(0), ArchivoPlanoBE.ArchivoPlanoRow)

        db.AddInParameter(dbCommand, "@ArchivoCodigo", DbType.String, oArchivoPlanoRow.ArchivoCodigo)
        db.AddInParameter(dbCommand, "@ArchivoNombre", DbType.String, oArchivoPlanoRow.ArchivoNombre)
        db.AddInParameter(dbCommand, "@ArchivoDescripcion", DbType.String, oArchivoPlanoRow.ArchivoDescripcion)
        db.AddInParameter(dbCommand, "@ArchivoExtension", DbType.String, oArchivoPlanoRow.ArchivoExtension)
        db.AddInParameter(dbCommand, "@ArchivoUbicacion", DbType.String, oArchivoPlanoRow.ArchivoUbicacion)
        db.AddInParameter(dbCommand, "@ArchivoTipoSeparador", DbType.String, oArchivoPlanoRow.ArchivoTipoSeparador)
        db.AddInParameter(dbCommand, "@ArchivoSeparador", DbType.String, oArchivoPlanoRow.ArchivoSeparador)
        db.AddInParameter(dbCommand, "@ArchivoLongitudRegistro", DbType.String, oArchivoPlanoRow.ArchivoLongitudRegistro)
        db.AddInParameter(dbCommand, "@ArchivoSeparadorDecimales", DbType.String, oArchivoPlanoRow.ArchivoSeparadorDecimales)
        db.AddInParameter(dbCommand, "@UsuarioModificacion", DbType.String, oArchivoPlanoRow.UsuarioModificacion)
        db.AddInParameter(dbCommand, "@FechaModificacion", DbType.Decimal, oArchivoPlanoRow.FechaModificacion)
        db.AddInParameter(dbCommand, "@HoraModificacion", DbType.String, oArchivoPlanoRow.HoraModificacion)
        db.ExecuteNonQuery(dbCommand)
        Return True

    End Function

    Public Function Eliminar(ByVal ArchivoCodigo As String, ByVal dataRequest As DataSet) As Boolean
        Dim db As Database = DatabaseFactory.CreateDatabase()
        Dim dbCommand As dbCommand = db.GetStoredProcCommand("ArchivoPlano_Eliminar")
        db.AddInParameter(dbCommand, "@ArchivoCodigo", DbType.String, ArchivoCodigo)

        db.ExecuteNonQuery(dbCommand)
        Return True
    End Function
    '''Publicado por Yanina Pérez
    '''Fecha Creación 10/12/2007
    '''Descripción Inserta registros de orden de inversión desde un txt
    Public Function InsertarDatosArchivo(ByVal drDatos As DataRow, ByVal dataRequest As DataSet) As Boolean
        Dim db As Database = DatabaseFactory.CreateDatabase()
        Dim sqlCommand As String = "OrdenInversionDATATEC_Insertar"
        Dim dbCommand As dbCommand = db.GetStoredProcCommand(sqlCommand)
        db.AddInParameter(dbCommand, "@p_CodigoPrimaryuser", DbType.String, drDatos.Item(0).ToString())
        db.AddInParameter(dbCommand, "@p_NoUsados", DbType.String, drDatos.Item(1).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoDataserver", DbType.String, drDatos.Item(2).ToString())
        db.AddInParameter(dbCommand, "@p_NumeroRemitente", DbType.String, drDatos.Item(3).ToString())
        db.AddInParameter(dbCommand, "@p_NumeroDataserver", DbType.String, drDatos.Item(4).ToString())
        db.AddInParameter(dbCommand, "@p_Log", DbType.String, drDatos.Item(5).ToString())
        db.AddInParameter(dbCommand, "@p_Usuario", DbType.String, drDatos.Item(6).ToString())
        db.AddInParameter(dbCommand, "@p_Hora", DbType.String, drDatos.Item(7).ToString())
        db.AddInParameter(dbCommand, "@p_Fecha", DbType.String, drDatos.Item(8).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoInstitucion", DbType.String, drDatos.Item(9).ToString())
        db.AddInParameter(dbCommand, "@p_Ciudad", DbType.String, drDatos.Item(10).ToString())
        db.AddInParameter(dbCommand, "@p_Agencia", DbType.String, drDatos.Item(11).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaInstitucionEspecialRemitente", DbType.String, drDatos.Item(12).ToString())
        db.AddInParameter(dbCommand, "@p_FuncionRemitente", DbType.String, drDatos.Item(13).ToString())
        db.AddInParameter(dbCommand, "@p_ClaseMensaje", DbType.String, drDatos.Item(14).ToString())
        db.AddInParameter(dbCommand, "@p_Bandera", DbType.String, drDatos.Item(15).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaPrioridad", DbType.String, drDatos.Item(16).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoPrimaryuserPostura", DbType.String, drDatos.Item(17).ToString())
        db.AddInParameter(dbCommand, "@p_UsuarioPostura", DbType.String, drDatos.Item(18).ToString())
        db.AddInParameter(dbCommand, "@p_McodPostura", DbType.String, drDatos.Item(19).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoInstitucionPostura", DbType.String, drDatos.Item(20).ToString())
        db.AddInParameter(dbCommand, "@p_Ciudad3cPostura", DbType.String, drDatos.Item(21).ToString())
        db.AddInParameter(dbCommand, "@p_AgenciaPostura", DbType.String, drDatos.Item(22).ToString())
        db.AddInParameter(dbCommand, "@p_Sucursal4cPostura", DbType.String, drDatos.Item(23).ToString())
        db.AddInParameter(dbCommand, "@p_CiudadPostura", DbType.String, drDatos.Item(24).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoInstitucionBancoPostura", DbType.String, drDatos.Item(25).ToString())
        db.AddInParameter(dbCommand, "@p_Ciudad3cBancoPostura", DbType.String, drDatos.Item(26).ToString())
        db.AddInParameter(dbCommand, "@p_AgenciaBancoPostura", DbType.String, drDatos.Item(27).ToString())
        db.AddInParameter(dbCommand, "@p_Sucursal4cBancoPostura", DbType.String, drDatos.Item(28).ToString())
        db.AddInParameter(dbCommand, "@p_CiudadBancoPostura", DbType.String, drDatos.Item(29).ToString())
        db.AddInParameter(dbCommand, "@p_UsuarioBanco", DbType.String, drDatos.Item(30).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaClienteEtcPostura", DbType.String, drDatos.Item(31).ToString())
        db.AddInParameter(dbCommand, "@p_RellenoPostulante", DbType.String, drDatos.Item(32).ToString())
        db.AddInParameter(dbCommand, "@p_Mercado", DbType.String, drDatos.Item(33).ToString())
        db.AddInParameter(dbCommand, "@p_SubMercado", DbType.String, drDatos.Item(34).ToString())
        db.AddInParameter(dbCommand, "@p_OD", DbType.String, drDatos.Item(35).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaViaProcesamiento", DbType.String, drDatos.Item(36).ToString())
        db.AddInParameter(dbCommand, "@p_HoraOperacion", DbType.String, drDatos.Item(37).ToString())
        db.AddInParameter(dbCommand, "@p_TicksOperacion", DbType.String, drDatos.Item(38).ToString())
        db.AddInParameter(dbCommand, "@p_HoraParaTitilar", DbType.String, drDatos.Item(39).ToString())
        db.AddInParameter(dbCommand, "@p_FechaPostura", DbType.String, drDatos.Item(40).ToString())
        db.AddInParameter(dbCommand, "@p_HoraPostura", DbType.String, drDatos.Item(41).ToString())
        db.AddInParameter(dbCommand, "@p_TotalPostura", DbType.String, drDatos.Item(42).ToString())
        db.AddInParameter(dbCommand, "@p_FechaValor", DbType.String, drDatos.Item(43).ToString())
        db.AddInParameter(dbCommand, "@p_FechaEntrega", DbType.String, drDatos.Item(44).ToString())
        db.AddInParameter(dbCommand, "@p_Dias", DbType.String, drDatos.Item(45).ToString())
        db.AddInParameter(dbCommand, "@p_Xdias", DbType.String, drDatos.Item(46).ToString())
        db.AddInParameter(dbCommand, "@p_FechaVencimientoXdias", DbType.String, drDatos.Item(47).ToString())
        db.AddInParameter(dbCommand, "@p_Nivel", DbType.String, drDatos.Item(48).ToString())
        db.AddInParameter(dbCommand, "@p_TextoTerm", DbType.String, drDatos.Item(49).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaFisicoCompensacion", DbType.String, drDatos.Item(50).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaEstandarLibre", DbType.String, drDatos.Item(51).ToString())
        db.AddInParameter(dbCommand, "@p_IdentificadorGrupoPosturasA", DbType.String, drDatos.Item(52).ToString())
        db.AddInParameter(dbCommand, "@p_IdentificadorGrupoPosturasB", DbType.String, drDatos.Item(53).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaRetirarPosturaTransParcial", DbType.String, drDatos.Item(54).ToString())
        db.AddInParameter(dbCommand, "@p_Precio", DbType.String, drDatos.Item(55).ToString())
        db.AddInParameter(dbCommand, "@p_PointsForward", DbType.String, drDatos.Item(56).ToString())
        db.AddInParameter(dbCommand, "@p_Numero", DbType.String, drDatos.Item(57).ToString())
        db.AddInParameter(dbCommand, "@p_NumeroMinimo", DbType.String, drDatos.Item(58).ToString())
        db.AddInParameter(dbCommand, "@p_NumeroTransado", DbType.String, drDatos.Item(59).ToString())
        db.AddInParameter(dbCommand, "@p_NumeroTotal", DbType.String, drDatos.Item(60).ToString())
        db.AddInParameter(dbCommand, "@p_FraccionBasica", DbType.String, drDatos.Item(61).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaMinimo", DbType.String, drDatos.Item(62).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaFormaAdjudicacion", DbType.String, drDatos.Item(63).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaOperacionAutomatica", DbType.String, drDatos.Item(64).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaAjustePrecio", DbType.String, drDatos.Item(65).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaIngresadaConCalculos", DbType.String, drDatos.Item(66).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaTipoPostura", DbType.String, drDatos.Item(67).ToString())
        db.AddInParameter(dbCommand, "@p_OverrideIndicative", DbType.String, drDatos.Item(68).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaPosturaPendiente", DbType.String, drDatos.Item(69).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaEnlazadaPorMonto", DbType.String, drDatos.Item(70).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaEfectivoCheque", DbType.String, drDatos.Item(71).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaClasePostura", DbType.String, drDatos.Item(72).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaSubClasePostura", DbType.String, drDatos.Item(73).ToString())
        db.AddInParameter(dbCommand, "@p_DiasEnlace", DbType.String, drDatos.Item(74).ToString())
        db.AddInParameter(dbCommand, "@p_XdiasEnlace", DbType.String, drDatos.Item(75).ToString())
        db.AddInParameter(dbCommand, "@p_NivelEnlace", DbType.String, drDatos.Item(76).ToString())
        db.AddInParameter(dbCommand, "@p_FechaVencimientoEnlace", DbType.String, drDatos.Item(77).ToString())
        db.AddInParameter(dbCommand, "@p_TextoTermEnlace", DbType.String, drDatos.Item(78).ToString())
        db.AddInParameter(dbCommand, "@p_SubMercadoEnlace", DbType.String, drDatos.Item(79).ToString())
        db.AddInParameter(dbCommand, "@p_ODEnlace", DbType.String, drDatos.Item(80).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaPosturaConExpiracion", DbType.String, drDatos.Item(81).ToString())
        db.AddInParameter(dbCommand, "@p_HoraExpiracionPostura", DbType.String, drDatos.Item(82).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaEnlaceAPrecioSpot", DbType.String, drDatos.Item(83).ToString())
        db.AddInParameter(dbCommand, "@p_PrecioSpotMinimo", DbType.String, drDatos.Item(84).ToString())
        db.AddInParameter(dbCommand, "@p_PrecioSpotMaximo", DbType.String, drDatos.Item(85).ToString())
        db.AddInParameter(dbCommand, "@p_UsuarioOrdenEnlace", DbType.String, drDatos.Item(86).ToString())
        db.AddInParameter(dbCommand, "@p_McodOrdenEnlaces", DbType.String, drDatos.Item(87).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoInstitucionIntermediariaPostura", DbType.String, drDatos.Item(88).ToString())
        db.AddInParameter(dbCommand, "@p_Ciudad3cIntermediariaPostura", DbType.String, drDatos.Item(89).ToString())
        db.AddInParameter(dbCommand, "@p_AgenciaIntermediariaPostura", DbType.String, drDatos.Item(90).ToString())
        db.AddInParameter(dbCommand, "@p_Sucursal4cIntermediariaPostura", DbType.String, drDatos.Item(91).ToString())
        db.AddInParameter(dbCommand, "@p_CiudadIntermediariaPostura", DbType.String, drDatos.Item(92).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaViaIntermediarioPostura", DbType.String, drDatos.Item(93).ToString())
        db.AddInParameter(dbCommand, "@p_RellenoPostura", DbType.String, drDatos.Item(94).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaPosturaEspecifica", DbType.String, drDatos.Item(95).ToString())
        db.AddInParameter(dbCommand, "@p_UsuarioPosturaOriginal", DbType.String, drDatos.Item(96).ToString())
        db.AddInParameter(dbCommand, "@p_McodPosturaOriginal", DbType.String, drDatos.Item(97).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaCorretaje", DbType.String, drDatos.Item(98).ToString())
        db.AddInParameter(dbCommand, "@p_ComisionPostura", DbType.String, drDatos.Item(99).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaComision", DbType.String, drDatos.Item(100).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoEntidadPublica", DbType.String, drDatos.Item(101).ToString())
        db.AddInParameter(dbCommand, "@p_EntidadPublica3c", DbType.String, drDatos.Item(102).ToString())
        db.AddInParameter(dbCommand, "@p_UsuarioEquipo", DbType.String, drDatos.Item(103).ToString())
        db.AddInParameter(dbCommand, "@p_Region", DbType.String, drDatos.Item(104).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaPreferencia", DbType.String, drDatos.Item(105).ToString())
        db.AddInParameter(dbCommand, "@p_Cruzada", DbType.String, drDatos.Item(106).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoEntidadPublicaAviso", DbType.String, drDatos.Item(107).ToString())
        db.AddInParameter(dbCommand, "@p_EntidadPublica3cAviso", DbType.String, drDatos.Item(108).ToString())
        db.AddInParameter(dbCommand, "@p_RellenoDatosMercadosAccPap", DbType.String, drDatos.Item(109).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoTitulo", DbType.String, drDatos.Item(110).ToString())
        db.AddInParameter(dbCommand, "@p_DelimCodigoTitulo", DbType.String, drDatos.Item(111).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoPais", DbType.String, drDatos.Item(112).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoEmisor", DbType.String, drDatos.Item(113).ToString())
        db.AddInParameter(dbCommand, "@p_Referencia", DbType.String, drDatos.Item(114).ToString())
        db.AddInParameter(dbCommand, "@p_NumeroEmision", DbType.String, drDatos.Item(115).ToString())
        db.AddInParameter(dbCommand, "@p_NumeroTramo", DbType.String, drDatos.Item(116).ToString())
        db.AddInParameter(dbCommand, "@p_NumeroColocacion", DbType.String, drDatos.Item(117).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoTablaDesarrollo", DbType.String, drDatos.Item(118).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaVencimiento", DbType.String, drDatos.Item(119).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaIntereses", DbType.String, drDatos.Item(120).ToString())
        db.AddInParameter(dbCommand, "@p_TipoPapel", DbType.String, drDatos.Item(121).ToString())
        db.AddInParameter(dbCommand, "@p_Moneda", DbType.String, drDatos.Item(122).ToString())
        db.AddInParameter(dbCommand, "@p_Moneda1c", DbType.String, drDatos.Item(123).ToString())
        db.AddInParameter(dbCommand, "@p_ValorNominal", DbType.String, drDatos.Item(124).ToString())
        db.AddInParameter(dbCommand, "@p_LoteMaximo", DbType.String, drDatos.Item(125).ToString())
        db.AddInParameter(dbCommand, "@p_BaseDiasNumerador", DbType.String, drDatos.Item(126).ToString())
        db.AddInParameter(dbCommand, "@p_BaseDiasDenominador", DbType.String, drDatos.Item(127).ToString())
        db.AddInParameter(dbCommand, "@p_PeriodoCapital", DbType.String, drDatos.Item(128).ToString())
        db.AddInParameter(dbCommand, "@p_PeriodoInteres", DbType.String, drDatos.Item(129).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaPeriodoInteres", DbType.String, drDatos.Item(130).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaPeriodoCapital", DbType.String, drDatos.Item(131).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaDesmaterializadas", DbType.String, drDatos.Item(132).ToString())
        db.AddInParameter(dbCommand, "@p_TipoInteres", DbType.String, drDatos.Item(133).ToString())
        db.AddInParameter(dbCommand, "@p_TasaInteres", DbType.String, drDatos.Item(134).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaTipoTasa", DbType.String, drDatos.Item(135).ToString())
        db.AddInParameter(dbCommand, "@p_TasaReferencial", DbType.String, drDatos.Item(136).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoFormula", DbType.String, drDatos.Item(137).ToString())
        db.AddInParameter(dbCommand, "@p_Puntos", DbType.String, drDatos.Item(138).ToString())
        db.AddInParameter(dbCommand, "@p_Porcentaje", DbType.String, drDatos.Item(139).ToString())
        db.AddInParameter(dbCommand, "@p_FormulaReajuste", DbType.String, drDatos.Item(140).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaReajuste", DbType.String, drDatos.Item(141).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaPonderado", DbType.String, drDatos.Item(142).ToString())
        db.AddInParameter(dbCommand, "@p_PeriodoReajuste", DbType.String, drDatos.Item(143).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaPeriodoReajuste", DbType.String, drDatos.Item(144).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaReajustePeriodico", DbType.String, drDatos.Item(145).ToString())
        db.AddInParameter(dbCommand, "@p_ReferenciaTitulo", DbType.String, drDatos.Item(146).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoIsin", DbType.String, drDatos.Item(147).ToString())
        db.AddInParameter(dbCommand, "@p_FechaEmision", DbType.String, drDatos.Item(148).ToString())
        db.AddInParameter(dbCommand, "@p_FechaVencimiento", DbType.String, drDatos.Item(149).ToString())
        db.AddInParameter(dbCommand, "@p_PlazoTotal", DbType.String, drDatos.Item(150).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaPeriodico", DbType.String, drDatos.Item(151).ToString())
        db.AddInParameter(dbCommand, "@p_DiasReajustabilidad", DbType.String, drDatos.Item(152).ToString())
        db.AddInParameter(dbCommand, "@p_SaldoAmortizar", DbType.String, drDatos.Item(153).ToString())
        db.AddInParameter(dbCommand, "@p_InicioCuponVigenteInt", DbType.String, drDatos.Item(154).ToString())
        db.AddInParameter(dbCommand, "@p_VencimientoCuponVigenteInt", DbType.String, drDatos.Item(155).ToString())
        db.AddInParameter(dbCommand, "@p_InicioCuponVigenteCap", DbType.String, drDatos.Item(156).ToString())
        db.AddInParameter(dbCommand, "@p_VencimientoCuponVigenteCap", DbType.String, drDatos.Item(157).ToString())
        db.AddInParameter(dbCommand, "@p_Interes1", DbType.String, drDatos.Item(158).ToString())
        db.AddInParameter(dbCommand, "@p_Interes2", DbType.String, drDatos.Item(159).ToString())
        db.AddInParameter(dbCommand, "@p_FechaReajuste", DbType.String, drDatos.Item(160).ToString())
        db.AddInParameter(dbCommand, "@p_InicioReajusteVigente", DbType.String, drDatos.Item(161).ToString())
        db.AddInParameter(dbCommand, "@p_VencimientoReajusteVigente", DbType.String, drDatos.Item(162).ToString())
        db.AddInParameter(dbCommand, "@p_NumeroTitulos", DbType.String, drDatos.Item(163).ToString())
        db.AddInParameter(dbCommand, "@p_MontoEmitido", DbType.String, drDatos.Item(164).ToString())
        db.AddInParameter(dbCommand, "@p_CuponesSobrepuestos", DbType.String, drDatos.Item(165).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoGrupo", DbType.String, drDatos.Item(166).ToString())
        db.AddInParameter(dbCommand, "@p_Restriccion", DbType.String, drDatos.Item(167).ToString())
        db.AddInParameter(dbCommand, "@p_Concertacion", DbType.String, drDatos.Item(168).ToString())
        db.AddInParameter(dbCommand, "@p_Error", DbType.String, drDatos.Item(169).ToString())
        db.AddInParameter(dbCommand, "@p_RestriccionParaOrdenamiento", DbType.String, drDatos.Item(170).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaRestablecerHechos", DbType.String, drDatos.Item(171).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoSuperGrupo", DbType.String, drDatos.Item(172).ToString())
        db.AddInParameter(dbCommand, "@p_Linea", DbType.String, drDatos.Item(173).ToString())
        db.AddInParameter(dbCommand, "@p_Liquidacion", DbType.String, drDatos.Item(174).ToString())
        db.AddInParameter(dbCommand, "@p_PlazoXVencer", DbType.String, drDatos.Item(175).ToString())
        db.AddInParameter(dbCommand, "@p_PeriodosTotalesGraciaCapital", DbType.String, drDatos.Item(176).ToString())
        db.AddInParameter(dbCommand, "@p_Relleno", DbType.String, drDatos.Item(177).ToString())
        db.AddInParameter(dbCommand, "@p_SubtipoPapel", DbType.String, drDatos.Item(178).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaIndiceIngresado", DbType.String, drDatos.Item(179).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaProvisional", DbType.String, drDatos.Item(180).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaEmision", DbType.String, drDatos.Item(181).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaMecanismo", DbType.String, drDatos.Item(182).ToString())
        db.AddInParameter(dbCommand, "@p_ClasePapel", DbType.String, drDatos.Item(183).ToString())
        db.AddInParameter(dbCommand, "@p_VencimientoReal", DbType.String, drDatos.Item(184).ToString())
        db.AddInParameter(dbCommand, "@p_DiasReal", DbType.String, drDatos.Item(185).ToString())
        db.AddInParameter(dbCommand, "@p_PlazoTotalReal", DbType.String, drDatos.Item(186).ToString())
        db.AddInParameter(dbCommand, "@p_Cupon", DbType.String, drDatos.Item(187).ToString())
        db.AddInParameter(dbCommand, "@p_CartaCompromiso", DbType.String, drDatos.Item(188).ToString())
        db.AddInParameter(dbCommand, "@p_Rendimiento", DbType.String, drDatos.Item(189).ToString())
        db.AddInParameter(dbCommand, "@p_Rentabilidad", DbType.String, drDatos.Item(190).ToString())
        db.AddInParameter(dbCommand, "@p_Term", DbType.String, drDatos.Item(191).ToString())
        db.AddInParameter(dbCommand, "@p_Descuento", DbType.String, drDatos.Item(192).ToString())
        db.AddInParameter(dbCommand, "@p_DiasTranscurridos", DbType.String, drDatos.Item(193).ToString())
        db.AddInParameter(dbCommand, "@p_DiasResta", DbType.String, drDatos.Item(194).ToString())
        db.AddInParameter(dbCommand, "@p_DiasUltimoPeriodo", DbType.String, drDatos.Item(195).ToString())
        db.AddInParameter(dbCommand, "@p_InteresesDevengados", DbType.String, drDatos.Item(196).ToString())
        db.AddInParameter(dbCommand, "@p_ValorANegociar", DbType.String, drDatos.Item(197).ToString())
        db.AddInParameter(dbCommand, "@p_ValorEfectivo", DbType.String, drDatos.Item(198).ToString())
        db.AddInParameter(dbCommand, "@p_ValorTotal", DbType.String, drDatos.Item(199).ToString())
        db.AddInParameter(dbCommand, "@p_ValorMinimoSubasta", DbType.String, drDatos.Item(200).ToString())
        db.AddInParameter(dbCommand, "@p_Decreto", DbType.String, drDatos.Item(201).ToString())
        db.AddInParameter(dbCommand, "@p_RellenoDatosMercadosPapeles", DbType.String, drDatos.Item(202).ToString())
        db.AddInParameter(dbCommand, "@p_Accion", DbType.String, drDatos.Item(203).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaSuspension", DbType.String, drDatos.Item(204).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaPosturaMercado", DbType.String, drDatos.Item(205).ToString())
        db.AddInParameter(dbCommand, "@p_EscalaPrecio", DbType.String, drDatos.Item(206).ToString())
        db.AddInParameter(dbCommand, "@p_PicturePrecio", DbType.String, drDatos.Item(207).ToString())
        db.AddInParameter(dbCommand, "@p_PicturePrecioFinal", DbType.String, drDatos.Item(208).ToString())
        db.AddInParameter(dbCommand, "@p_DivisorPrecio", DbType.String, drDatos.Item(209).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaDerechos", DbType.String, drDatos.Item(210).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaPosturasEnCombinada", DbType.String, drDatos.Item(211).ToString())
        db.AddInParameter(dbCommand, "@p_RellenoDatosMercadosAcciones", DbType.String, drDatos.Item(212).ToString())
        db.AddInParameter(dbCommand, "@p_TasaDolares", DbType.String, drDatos.Item(213).ToString())
        db.AddInParameter(dbCommand, "@p_TasaMonedaLocal", DbType.String, drDatos.Item(214).ToString())
        db.AddInParameter(dbCommand, "@p_TasaLibor", DbType.String, drDatos.Item(215).ToString())
        db.AddInParameter(dbCommand, "@p_TasaSpread", DbType.String, drDatos.Item(216).ToString())
        db.AddInParameter(dbCommand, "@p_Billetes1Dolar", DbType.String, drDatos.Item(217).ToString())
        db.AddInParameter(dbCommand, "@p_Billetes5Dolares", DbType.String, drDatos.Item(218).ToString())
        db.AddInParameter(dbCommand, "@p_Billetes10Dolares", DbType.String, drDatos.Item(219).ToString())
        db.AddInParameter(dbCommand, "@p_Billetes20Dolares", DbType.String, drDatos.Item(220).ToString())
        db.AddInParameter(dbCommand, "@p_Billetes50Dolares", DbType.String, drDatos.Item(221).ToString())
        db.AddInParameter(dbCommand, "@p_Billetes100Dolares", DbType.String, drDatos.Item(222).ToString())
        db.AddInParameter(dbCommand, "@p_Billetes2Dolar", DbType.String, drDatos.Item(223).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaEntregaBilletes", DbType.String, drDatos.Item(224).ToString())
        db.AddInParameter(dbCommand, "@p_NumeroRueda", DbType.String, drDatos.Item(225).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoInstitDirectorRueda", DbType.String, drDatos.Item(226).ToString())
        db.AddInParameter(dbCommand, "@p_HoraCierreSubasta", DbType.String, drDatos.Item(227).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaFormaRueda", DbType.String, drDatos.Item(228).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaTasa", DbType.String, drDatos.Item(229).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaAdjudicacion", DbType.String, drDatos.Item(230).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaCuantaTransferencia", DbType.String, drDatos.Item(231).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaConfirmadoDirector", DbType.String, drDatos.Item(232).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaRetiroCustodia", DbType.String, drDatos.Item(233).ToString())
        db.AddInParameter(dbCommand, "@p_OrigenPostura", DbType.String, drDatos.Item(234).ToString())
        db.AddInParameter(dbCommand, "@p_Precio2", DbType.String, drDatos.Item(235).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaPlazo", DbType.String, drDatos.Item(236).ToString())
        db.AddInParameter(dbCommand, "@p_RellenoDatosRueda", DbType.String, drDatos.Item(237).ToString())
        db.AddInParameter(dbCommand, "@p_RendimientoAsignado", DbType.String, drDatos.Item(238).ToString())
        db.AddInParameter(dbCommand, "@p_NumeroPedido", DbType.String, drDatos.Item(239).ToString())
        db.AddInParameter(dbCommand, "@p_NumeroAsignado", DbType.String, drDatos.Item(240).ToString())
        db.AddInParameter(dbCommand, "@p_PrecioAsignado", DbType.String, drDatos.Item(241).ToString())
        db.AddInParameter(dbCommand, "@p_MontoEfectivoAsignado", DbType.String, drDatos.Item(242).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaODAsignacion", DbType.String, drDatos.Item(243).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoPosturaAceptacion", DbType.String, drDatos.Item(244).ToString())
        db.AddInParameter(dbCommand, "@p_NumeroLiquidacion", DbType.String, drDatos.Item(245).ToString())
        db.AddInParameter(dbCommand, "@p_HoraExpiracion", DbType.String, drDatos.Item(246).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaRevisarCalce", DbType.String, drDatos.Item(247).ToString())
        db.AddInParameter(dbCommand, "@p_RellenoDatosAdicionales", DbType.String, drDatos.Item(248).ToString())
        db.AddInParameter(dbCommand, "@p_PrecioSpot", DbType.String, drDatos.Item(249).ToString())
        db.AddInParameter(dbCommand, "@p_PrecioFinal", DbType.String, drDatos.Item(250).ToString())
        db.AddInParameter(dbCommand, "@p_Iva", DbType.String, drDatos.Item(251).ToString())
        db.AddInParameter(dbCommand, "@p_PuntosFw", DbType.String, drDatos.Item(252).ToString())
        db.AddInParameter(dbCommand, "@p_MarcaPrecio", DbType.String, drDatos.Item(253).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaTransaccionParaPostulantes", DbType.String, drDatos.Item(254).ToString())
        db.AddInParameter(dbCommand, "@p_McodTransaccion", DbType.String, drDatos.Item(255).ToString())
        db.AddInParameter(dbCommand, "@p_Contador", DbType.String, drDatos.Item(256).ToString())
        db.AddInParameter(dbCommand, "@p_BanderasTransaccion", DbType.String, drDatos.Item(257).ToString())
        db.AddInParameter(dbCommand, "@p_RellenoDatosAdicionalesTransaccion", DbType.String, drDatos.Item(258).ToString())
        db.AddInParameter(dbCommand, "@p_UsuarioPostura1", DbType.String, drDatos.Item(259).ToString())
        db.AddInParameter(dbCommand, "@p_McodPostura1", DbType.String, drDatos.Item(260).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoInstitucionPostura1", DbType.String, drDatos.Item(261).ToString())
        db.AddInParameter(dbCommand, "@p_Ciudad3cPostura1", DbType.String, drDatos.Item(262).ToString())
        db.AddInParameter(dbCommand, "@p_AgenciaPostura1", DbType.String, drDatos.Item(263).ToString())
        db.AddInParameter(dbCommand, "@p_Sucursal4cPostura1", DbType.String, drDatos.Item(264).ToString())
        db.AddInParameter(dbCommand, "@p_CiudadPostura1", DbType.String, drDatos.Item(265).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoInstitucionBancoPostura1", DbType.String, drDatos.Item(266).ToString())
        db.AddInParameter(dbCommand, "@p_Ciudad3cBancoPostura1", DbType.String, drDatos.Item(267).ToString())
        db.AddInParameter(dbCommand, "@p_AgenciaBancoPostura1", DbType.String, drDatos.Item(268).ToString())
        db.AddInParameter(dbCommand, "@p_Sucursal4cBancoPostura1", DbType.String, drDatos.Item(269).ToString())
        db.AddInParameter(dbCommand, "@p_CiudadBancoPostura1", DbType.String, drDatos.Item(270).ToString())
        db.AddInParameter(dbCommand, "@p_UsuarioBanco1", DbType.String, drDatos.Item(271).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaClienteEtcPostura1", DbType.String, drDatos.Item(272).ToString())
        db.AddInParameter(dbCommand, "@p_TotalPostura1", DbType.String, drDatos.Item(273).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaAceptacion", DbType.String, drDatos.Item(274).ToString())
        db.AddInParameter(dbCommand, "@p_HoraAceptacion", DbType.String, drDatos.Item(275).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoInstitucionIntermediaria", DbType.String, drDatos.Item(276).ToString())
        db.AddInParameter(dbCommand, "@p_Ciudad3cIntermediaria", DbType.String, drDatos.Item(277).ToString())
        db.AddInParameter(dbCommand, "@p_AgenciaIntermediaria", DbType.String, drDatos.Item(278).ToString())
        db.AddInParameter(dbCommand, "@p_Sucursal4cIntermediaria", DbType.String, drDatos.Item(279).ToString())
        db.AddInParameter(dbCommand, "@p_CiudadIntermediaria", DbType.String, drDatos.Item(280).ToString())
        db.AddInParameter(dbCommand, "@p_UsuarioSucursalIntermediario", DbType.String, drDatos.Item(281).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoInstitucionIntermediaria1", DbType.String, drDatos.Item(282).ToString())
        db.AddInParameter(dbCommand, "@p_Ciudad3cIntermediaria1", DbType.String, drDatos.Item(283).ToString())
        db.AddInParameter(dbCommand, "@p_AgenciaIntermediaria1", DbType.String, drDatos.Item(284).ToString())
        db.AddInParameter(dbCommand, "@p_Sucursal4cIntermediaria1", DbType.String, drDatos.Item(285).ToString())
        db.AddInParameter(dbCommand, "@p_CiudadIntermediaria1", DbType.String, drDatos.Item(286).ToString())
        db.AddInParameter(dbCommand, "@p_UsuarioSucursalIntermediario1", DbType.String, drDatos.Item(287).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaBrokerageComprador", DbType.String, drDatos.Item(288).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaBrokerageVendedor", DbType.String, drDatos.Item(289).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaViaIntermediarioComprador", DbType.String, drDatos.Item(290).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaViaIntermediarioVendedor", DbType.String, drDatos.Item(291).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoPrimaryuserPostura1", DbType.String, drDatos.Item(292).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaRegistraConOtr", DbType.String, drDatos.Item(293).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaOnOffScreen", DbType.String, drDatos.Item(294).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaCambianCamposAdicionales", DbType.String, drDatos.Item(295).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaAceptacionPendiente", DbType.String, drDatos.Item(296).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaProcedencia", DbType.String, drDatos.Item(297).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaModificadorPrioridad", DbType.String, drDatos.Item(298).ToString())
        db.AddInParameter(dbCommand, "@p_ComisionPostura1", DbType.String, drDatos.Item(299).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaComision1", DbType.String, drDatos.Item(300).ToString())
        db.AddInParameter(dbCommand, "@p_ComisionBolsa1", DbType.String, drDatos.Item(301).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoEntidadPublica1", DbType.String, drDatos.Item(302).ToString())
        db.AddInParameter(dbCommand, "@p_EntidadPublica3c1", DbType.String, drDatos.Item(303).ToString())
        db.AddInParameter(dbCommand, "@p_RellenoDatosAceptacion1", DbType.String, drDatos.Item(304).ToString())
        db.AddInParameter(dbCommand, "@p_IdentificadorLinkA", DbType.String, drDatos.Item(305).ToString())
        db.AddInParameter(dbCommand, "@p_IdentificadorLinkB", DbType.String, drDatos.Item(306).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaBrokerPostura1", DbType.String, drDatos.Item(307).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaPrecioAceptado", DbType.String, drDatos.Item(308).ToString())
        db.AddInParameter(dbCommand, "@p_BanderasPostura1", DbType.String, drDatos.Item(309).ToString())
        db.AddInParameter(dbCommand, "@p_RellenoDatosAceptacion", DbType.String, drDatos.Item(310).ToString())
        db.AddInParameter(dbCommand, "@p_UsuarioSolicitante", DbType.String, drDatos.Item(311).ToString())
        db.AddInParameter(dbCommand, "@p_HoraOriginal", DbType.String, drDatos.Item(312).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaRetiroParaModificar", DbType.String, drDatos.Item(313).ToString())
        db.AddInParameter(dbCommand, "@p_BanderaHoraOriginal", DbType.String, drDatos.Item(314).ToString())
        db.AddInParameter(dbCommand, "@p_RellenoDatosAnulacionModificacion", DbType.String, drDatos.Item(315).ToString())
        db.ExecuteNonQuery(dbCommand)
        Return True
    End Function


    Public Function Insertar_OrdenInversionDATATEC(ByVal drDatos As DataRow, ByVal dataRequest As DataSet) As Boolean
        Dim db As Database = DatabaseFactory.CreateDatabase()
        Dim sqlCommand As String = "Insertar_OrdenInversionDATATEC"
        Dim dbCommand As dbCommand = db.GetStoredProcCommand(sqlCommand)

        db.AddInParameter(dbCommand, "@p_FechaEntrega", DbType.String, drDatos.Item(44).ToString())
        db.AddInParameter(dbCommand, "@p_Precio", DbType.String, drDatos.Item(55).ToString())
        db.AddInParameter(dbCommand, "@p_Moneda", DbType.String, drDatos.Item(122).ToString())
        db.AddInParameter(dbCommand, "@p_ValorNominal", DbType.String, drDatos.Item(124).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoIsin", DbType.String, drDatos.Item(147).ToString())
        db.AddInParameter(dbCommand, "@p_Rentabilidad", DbType.String, drDatos.Item(190).ToString())
        db.AddInParameter(dbCommand, "@p_InteresesDevengados", DbType.String, drDatos.Item(196).ToString())
        db.AddInParameter(dbCommand, "@p_ValorANegociar", DbType.String, drDatos.Item(197).ToString())
        'ini HDG INC 61167	20100922
        'db.AddInParameter(dbCommand, "@p_CodigoInstitucionIntermediaria", DbType.String, drDatos.Item(276).ToString())
        'db.AddInParameter(dbCommand, "@p_BanderaOperacionAutomatica", DbType.String, drDatos.Item(64).ToString())
        db.AddInParameter(dbCommand, "@p_CodigoInstitucionIntermediaria", DbType.String, drDatos.Item(23).ToString())
        db.AddInParameter(dbCommand, "@p_OD", DbType.String, drDatos.Item(35).ToString())
        'fin HDG INC 61167	20100922
        db.ExecuteNonQuery(dbCommand)
        Return True
        'Return db.ExecuteDataSet(dbCommand)
    End Function

#Region "Otros Campos"

    'db.AddInParameter(dbCommand, "@p_CodigoPrimaryuser", DbType.String, drDatos.Item(0).ToString())
    'db.AddInParameter(dbCommand, "@p_NoUsados", DbType.String, drDatos.Item(1).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoDataserver", DbType.String, drDatos.Item(2).ToString())
    'db.AddInParameter(dbCommand, "@p_NumeroRemitente", DbType.String, drDatos.Item(3).ToString())
    'db.AddInParameter(dbCommand, "@p_NumeroDataserver", DbType.String, drDatos.Item(4).ToString())
    'db.AddInParameter(dbCommand, "@p_Log", DbType.String, drDatos.Item(5).ToString())
    'db.AddInParameter(dbCommand, "@p_Usuario", DbType.String, drDatos.Item(6).ToString())
    'db.AddInParameter(dbCommand, "@p_Hora", DbType.String, drDatos.Item(7).ToString())
    'db.AddInParameter(dbCommand, "@p_Fecha", DbType.String, drDatos.Item(8).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoInstitucion", DbType.String, drDatos.Item(9).ToString())
    'db.AddInParameter(dbCommand, "@p_Ciudad", DbType.String, drDatos.Item(10).ToString())
    'db.AddInParameter(dbCommand, "@p_Agencia", DbType.String, drDatos.Item(11).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaInstitucionEspecialRemitente", DbType.String, drDatos.Item(12).ToString())
    'db.AddInParameter(dbCommand, "@p_FuncionRemitente", DbType.String, drDatos.Item(13).ToString())
    'db.AddInParameter(dbCommand, "@p_ClaseMensaje", DbType.String, drDatos.Item(14).ToString())
    'db.AddInParameter(dbCommand, "@p_Bandera", DbType.String, drDatos.Item(15).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaPrioridad", DbType.String, drDatos.Item(16).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoPrimaryuserPostura", DbType.String, drDatos.Item(17).ToString())
    'db.AddInParameter(dbCommand, "@p_UsuarioPostura", DbType.String, drDatos.Item(18).ToString())
    'db.AddInParameter(dbCommand, "@p_McodPostura", DbType.String, drDatos.Item(19).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoInstitucionPostura", DbType.String, drDatos.Item(20).ToString())
    'db.AddInParameter(dbCommand, "@p_Ciudad3cPostura", DbType.String, drDatos.Item(21).ToString())
    'db.AddInParameter(dbCommand, "@p_AgenciaPostura", DbType.String, drDatos.Item(22).ToString())
    'db.AddInParameter(dbCommand, "@p_Sucursal4cPostura", DbType.String, drDatos.Item(23).ToString())
    'db.AddInParameter(dbCommand, "@p_CiudadPostura", DbType.String, drDatos.Item(24).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoInstitucionBancoPostura", DbType.String, drDatos.Item(25).ToString())
    'db.AddInParameter(dbCommand, "@p_Ciudad3cBancoPostura", DbType.String, drDatos.Item(26).ToString())
    'db.AddInParameter(dbCommand, "@p_AgenciaBancoPostura", DbType.String, drDatos.Item(27).ToString())
    'db.AddInParameter(dbCommand, "@p_Sucursal4cBancoPostura", DbType.String, drDatos.Item(28).ToString())
    'db.AddInParameter(dbCommand, "@p_CiudadBancoPostura", DbType.String, drDatos.Item(29).ToString())
    'db.AddInParameter(dbCommand, "@p_UsuarioBanco", DbType.String, drDatos.Item(30).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaClienteEtcPostura", DbType.String, drDatos.Item(31).ToString())
    'db.AddInParameter(dbCommand, "@p_RellenoPostulante", DbType.String, drDatos.Item(32).ToString())
    'db.AddInParameter(dbCommand, "@p_Mercado", DbType.String, drDatos.Item(33).ToString())
    'db.AddInParameter(dbCommand, "@p_SubMercado", DbType.String, drDatos.Item(34).ToString())
    'db.AddInParameter(dbCommand, "@p_OD", DbType.String, drDatos.Item(35).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaViaProcesamiento", DbType.String, drDatos.Item(36).ToString())
    'db.AddInParameter(dbCommand, "@p_HoraOperacion", DbType.String, drDatos.Item(37).ToString())
    'db.AddInParameter(dbCommand, "@p_TicksOperacion", DbType.String, drDatos.Item(38).ToString())
    'db.AddInParameter(dbCommand, "@p_HoraParaTitilar", DbType.String, drDatos.Item(39).ToString())
    'db.AddInParameter(dbCommand, "@p_FechaPostura", DbType.String, drDatos.Item(40).ToString())
    'db.AddInParameter(dbCommand, "@p_HoraPostura", DbType.String, drDatos.Item(41).ToString())
    'db.AddInParameter(dbCommand, "@p_TotalPostura", DbType.String, drDatos.Item(42).ToString())
    'db.AddInParameter(dbCommand, "@p_FechaValor", DbType.String, drDatos.Item(43).ToString())

    'db.AddInParameter(dbCommand, "@p_Dias", DbType.String, drDatos.Item(45).ToString())
    'db.AddInParameter(dbCommand, "@p_Xdias", DbType.String, drDatos.Item(46).ToString())
    'db.AddInParameter(dbCommand, "@p_FechaVencimientoXdias", DbType.String, drDatos.Item(47).ToString())
    'db.AddInParameter(dbCommand, "@p_Nivel", DbType.String, drDatos.Item(48).ToString())
    'db.AddInParameter(dbCommand, "@p_TextoTerm", DbType.String, drDatos.Item(49).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaFisicoCompensacion", DbType.String, drDatos.Item(50).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaEstandarLibre", DbType.String, drDatos.Item(51).ToString())
    'db.AddInParameter(dbCommand, "@p_IdentificadorGrupoPosturasA", DbType.String, drDatos.Item(52).ToString())
    'db.AddInParameter(dbCommand, "@p_IdentificadorGrupoPosturasB", DbType.String, drDatos.Item(53).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaRetirarPosturaTransParcial", DbType.String, drDatos.Item(54).ToString())

    'db.AddInParameter(dbCommand, "@p_PointsForward", DbType.String, drDatos.Item(56).ToString())
    'db.AddInParameter(dbCommand, "@p_Numero", DbType.String, drDatos.Item(57).ToString())
    'db.AddInParameter(dbCommand, "@p_NumeroMinimo", DbType.String, drDatos.Item(58).ToString())
    'db.AddInParameter(dbCommand, "@p_NumeroTransado", DbType.String, drDatos.Item(59).ToString())
    'db.AddInParameter(dbCommand, "@p_NumeroTotal", DbType.String, drDatos.Item(60).ToString())
    'db.AddInParameter(dbCommand, "@p_FraccionBasica", DbType.String, drDatos.Item(61).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaMinimo", DbType.String, drDatos.Item(62).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaFormaAdjudicacion", DbType.String, drDatos.Item(63).ToString())

    'db.AddInParameter(dbCommand, "@p_BanderaAjustePrecio", DbType.String, drDatos.Item(65).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaIngresadaConCalculos", DbType.String, drDatos.Item(66).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaTipoPostura", DbType.String, drDatos.Item(67).ToString())
    'db.AddInParameter(dbCommand, "@p_OverrideIndicative", DbType.String, drDatos.Item(68).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaPosturaPendiente", DbType.String, drDatos.Item(69).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaEnlazadaPorMonto", DbType.String, drDatos.Item(70).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaEfectivoCheque", DbType.String, drDatos.Item(71).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaClasePostura", DbType.String, drDatos.Item(72).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaSubClasePostura", DbType.String, drDatos.Item(73).ToString())
    'db.AddInParameter(dbCommand, "@p_DiasEnlace", DbType.String, drDatos.Item(74).ToString())
    'db.AddInParameter(dbCommand, "@p_XdiasEnlace", DbType.String, drDatos.Item(75).ToString())
    'db.AddInParameter(dbCommand, "@p_NivelEnlace", DbType.String, drDatos.Item(76).ToString())
    'db.AddInParameter(dbCommand, "@p_FechaVencimientoEnlace", DbType.String, drDatos.Item(77).ToString())
    'db.AddInParameter(dbCommand, "@p_TextoTermEnlace", DbType.String, drDatos.Item(78).ToString())
    'db.AddInParameter(dbCommand, "@p_SubMercadoEnlace", DbType.String, drDatos.Item(79).ToString())
    'db.AddInParameter(dbCommand, "@p_ODEnlace", DbType.String, drDatos.Item(80).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaPosturaConExpiracion", DbType.String, drDatos.Item(81).ToString())
    'db.AddInParameter(dbCommand, "@p_HoraExpiracionPostura", DbType.String, drDatos.Item(82).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaEnlaceAPrecioSpot", DbType.String, drDatos.Item(83).ToString())
    'db.AddInParameter(dbCommand, "@p_PrecioSpotMinimo", DbType.String, drDatos.Item(84).ToString())
    'db.AddInParameter(dbCommand, "@p_PrecioSpotMaximo", DbType.String, drDatos.Item(85).ToString())
    'db.AddInParameter(dbCommand, "@p_UsuarioOrdenEnlace", DbType.String, drDatos.Item(86).ToString())
    'db.AddInParameter(dbCommand, "@p_McodOrdenEnlaces", DbType.String, drDatos.Item(87).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoInstitucionIntermediariaPostura", DbType.String, drDatos.Item(88).ToString())
    'db.AddInParameter(dbCommand, "@p_Ciudad3cIntermediariaPostura", DbType.String, drDatos.Item(89).ToString())
    'db.AddInParameter(dbCommand, "@p_AgenciaIntermediariaPostura", DbType.String, drDatos.Item(90).ToString())
    'db.AddInParameter(dbCommand, "@p_Sucursal4cIntermediariaPostura", DbType.String, drDatos.Item(91).ToString())
    'db.AddInParameter(dbCommand, "@p_CiudadIntermediariaPostura", DbType.String, drDatos.Item(92).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaViaIntermediarioPostura", DbType.String, drDatos.Item(93).ToString())
    'db.AddInParameter(dbCommand, "@p_RellenoPostura", DbType.String, drDatos.Item(94).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaPosturaEspecifica", DbType.String, drDatos.Item(95).ToString())
    'db.AddInParameter(dbCommand, "@p_UsuarioPosturaOriginal", DbType.String, drDatos.Item(96).ToString())
    'db.AddInParameter(dbCommand, "@p_McodPosturaOriginal", DbType.String, drDatos.Item(97).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaCorretaje", DbType.String, drDatos.Item(98).ToString())
    'db.AddInParameter(dbCommand, "@p_ComisionPostura", DbType.String, drDatos.Item(99).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaComision", DbType.String, drDatos.Item(100).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoEntidadPublica", DbType.String, drDatos.Item(101).ToString())
    'db.AddInParameter(dbCommand, "@p_EntidadPublica3c", DbType.String, drDatos.Item(102).ToString())
    'db.AddInParameter(dbCommand, "@p_UsuarioEquipo", DbType.String, drDatos.Item(103).ToString())
    'db.AddInParameter(dbCommand, "@p_Region", DbType.String, drDatos.Item(104).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaPreferencia", DbType.String, drDatos.Item(105).ToString())
    'db.AddInParameter(dbCommand, "@p_Cruzada", DbType.String, drDatos.Item(106).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoEntidadPublicaAviso", DbType.String, drDatos.Item(107).ToString())
    'db.AddInParameter(dbCommand, "@p_EntidadPublica3cAviso", DbType.String, drDatos.Item(108).ToString())
    'db.AddInParameter(dbCommand, "@p_RellenoDatosMercadosAccPap", DbType.String, drDatos.Item(109).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoTitulo", DbType.String, drDatos.Item(110).ToString())
    'db.AddInParameter(dbCommand, "@p_DelimCodigoTitulo", DbType.String, drDatos.Item(111).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoPais", DbType.String, drDatos.Item(112).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoEmisor", DbType.String, drDatos.Item(113).ToString())
    'db.AddInParameter(dbCommand, "@p_Referencia", DbType.String, drDatos.Item(114).ToString())
    'db.AddInParameter(dbCommand, "@p_NumeroEmision", DbType.String, drDatos.Item(115).ToString())
    'db.AddInParameter(dbCommand, "@p_NumeroTramo", DbType.String, drDatos.Item(116).ToString())
    'db.AddInParameter(dbCommand, "@p_NumeroColocacion", DbType.String, drDatos.Item(117).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoTablaDesarrollo", DbType.String, drDatos.Item(118).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaVencimiento", DbType.String, drDatos.Item(119).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaIntereses", DbType.String, drDatos.Item(120).ToString())
    'db.AddInParameter(dbCommand, "@p_TipoPapel", DbType.String, drDatos.Item(121).ToString())

    'db.AddInParameter(dbCommand, "@p_Moneda1c", DbType.String, drDatos.Item(123).ToString())

    'db.AddInParameter(dbCommand, "@p_LoteMaximo", DbType.String, drDatos.Item(125).ToString())
    'db.AddInParameter(dbCommand, "@p_BaseDiasNumerador", DbType.String, drDatos.Item(126).ToString())
    'db.AddInParameter(dbCommand, "@p_BaseDiasDenominador", DbType.String, drDatos.Item(127).ToString())
    'db.AddInParameter(dbCommand, "@p_PeriodoCapital", DbType.String, drDatos.Item(128).ToString())
    'db.AddInParameter(dbCommand, "@p_PeriodoInteres", DbType.String, drDatos.Item(129).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaPeriodoInteres", DbType.String, drDatos.Item(130).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaPeriodoCapital", DbType.String, drDatos.Item(131).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaDesmaterializadas", DbType.String, drDatos.Item(132).ToString())
    'db.AddInParameter(dbCommand, "@p_TipoInteres", DbType.String, drDatos.Item(133).ToString())
    'db.AddInParameter(dbCommand, "@p_TasaInteres", DbType.String, drDatos.Item(134).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaTipoTasa", DbType.String, drDatos.Item(135).ToString())
    'db.AddInParameter(dbCommand, "@p_TasaReferencial", DbType.String, drDatos.Item(136).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoFormula", DbType.String, drDatos.Item(137).ToString())
    'db.AddInParameter(dbCommand, "@p_Puntos", DbType.String, drDatos.Item(138).ToString())
    'db.AddInParameter(dbCommand, "@p_Porcentaje", DbType.String, drDatos.Item(139).ToString())
    'db.AddInParameter(dbCommand, "@p_FormulaReajuste", DbType.String, drDatos.Item(140).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaReajuste", DbType.String, drDatos.Item(141).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaPonderado", DbType.String, drDatos.Item(142).ToString())
    'db.AddInParameter(dbCommand, "@p_PeriodoReajuste", DbType.String, drDatos.Item(143).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaPeriodoReajuste", DbType.String, drDatos.Item(144).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaReajustePeriodico", DbType.String, drDatos.Item(145).ToString())
    'db.AddInParameter(dbCommand, "@p_ReferenciaTitulo", DbType.String, drDatos.Item(146).ToString())

    'db.AddInParameter(dbCommand, "@p_FechaEmision", DbType.String, drDatos.Item(148).ToString())
    'db.AddInParameter(dbCommand, "@p_FechaVencimiento", DbType.String, drDatos.Item(149).ToString())
    'db.AddInParameter(dbCommand, "@p_PlazoTotal", DbType.String, drDatos.Item(150).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaPeriodico", DbType.String, drDatos.Item(151).ToString())
    'db.AddInParameter(dbCommand, "@p_DiasReajustabilidad", DbType.String, drDatos.Item(152).ToString())
    'db.AddInParameter(dbCommand, "@p_SaldoAmortizar", DbType.String, drDatos.Item(153).ToString())
    'db.AddInParameter(dbCommand, "@p_InicioCuponVigenteInt", DbType.String, drDatos.Item(154).ToString())
    'db.AddInParameter(dbCommand, "@p_VencimientoCuponVigenteInt", DbType.String, drDatos.Item(155).ToString())
    'db.AddInParameter(dbCommand, "@p_InicioCuponVigenteCap", DbType.String, drDatos.Item(156).ToString())
    'db.AddInParameter(dbCommand, "@p_VencimientoCuponVigenteCap", DbType.String, drDatos.Item(157).ToString())
    'db.AddInParameter(dbCommand, "@p_Interes1", DbType.String, drDatos.Item(158).ToString())
    'db.AddInParameter(dbCommand, "@p_Interes2", DbType.String, drDatos.Item(159).ToString())
    'db.AddInParameter(dbCommand, "@p_FechaReajuste", DbType.String, drDatos.Item(160).ToString())
    'db.AddInParameter(dbCommand, "@p_InicioReajusteVigente", DbType.String, drDatos.Item(161).ToString())
    'db.AddInParameter(dbCommand, "@p_VencimientoReajusteVigente", DbType.String, drDatos.Item(162).ToString())
    'db.AddInParameter(dbCommand, "@p_NumeroTitulos", DbType.String, drDatos.Item(163).ToString())
    'db.AddInParameter(dbCommand, "@p_MontoEmitido", DbType.String, drDatos.Item(164).ToString())
    'db.AddInParameter(dbCommand, "@p_CuponesSobrepuestos", DbType.String, drDatos.Item(165).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoGrupo", DbType.String, drDatos.Item(166).ToString())
    'db.AddInParameter(dbCommand, "@p_Restriccion", DbType.String, drDatos.Item(167).ToString())
    'db.AddInParameter(dbCommand, "@p_Concertacion", DbType.String, drDatos.Item(168).ToString())
    'db.AddInParameter(dbCommand, "@p_Error", DbType.String, drDatos.Item(169).ToString())
    'db.AddInParameter(dbCommand, "@p_RestriccionParaOrdenamiento", DbType.String, drDatos.Item(170).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaRestablecerHechos", DbType.String, drDatos.Item(171).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoSuperGrupo", DbType.String, drDatos.Item(172).ToString())
    'db.AddInParameter(dbCommand, "@p_Linea", DbType.String, drDatos.Item(173).ToString())
    'db.AddInParameter(dbCommand, "@p_Liquidacion", DbType.String, drDatos.Item(174).ToString())
    'db.AddInParameter(dbCommand, "@p_PlazoXVencer", DbType.String, drDatos.Item(175).ToString())
    'db.AddInParameter(dbCommand, "@p_PeriodosTotalesGraciaCapital", DbType.String, drDatos.Item(176).ToString())
    'db.AddInParameter(dbCommand, "@p_Relleno", DbType.String, drDatos.Item(177).ToString())
    'db.AddInParameter(dbCommand, "@p_SubtipoPapel", DbType.String, drDatos.Item(178).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaIndiceIngresado", DbType.String, drDatos.Item(179).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaProvisional", DbType.String, drDatos.Item(180).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaEmision", DbType.String, drDatos.Item(181).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaMecanismo", DbType.String, drDatos.Item(182).ToString())
    'db.AddInParameter(dbCommand, "@p_ClasePapel", DbType.String, drDatos.Item(183).ToString())
    'db.AddInParameter(dbCommand, "@p_VencimientoReal", DbType.String, drDatos.Item(184).ToString())
    'db.AddInParameter(dbCommand, "@p_DiasReal", DbType.String, drDatos.Item(185).ToString())
    'db.AddInParameter(dbCommand, "@p_PlazoTotalReal", DbType.String, drDatos.Item(186).ToString())
    'db.AddInParameter(dbCommand, "@p_Cupon", DbType.String, drDatos.Item(187).ToString())
    'db.AddInParameter(dbCommand, "@p_CartaCompromiso", DbType.String, drDatos.Item(188).ToString())
    'db.AddInParameter(dbCommand, "@p_Rendimiento", DbType.String, drDatos.Item(189).ToString())

    'db.AddInParameter(dbCommand, "@p_Term", DbType.String, drDatos.Item(191).ToString())
    'db.AddInParameter(dbCommand, "@p_Descuento", DbType.String, drDatos.Item(192).ToString())
    'db.AddInParameter(dbCommand, "@p_DiasTranscurridos", DbType.String, drDatos.Item(193).ToString())
    'db.AddInParameter(dbCommand, "@p_DiasResta", DbType.String, drDatos.Item(194).ToString())
    'db.AddInParameter(dbCommand, "@p_DiasUltimoPeriodo", DbType.String, drDatos.Item(195).ToString())


    'db.AddInParameter(dbCommand, "@p_ValorEfectivo", DbType.String, drDatos.Item(198).ToString())
    'db.AddInParameter(dbCommand, "@p_ValorTotal", DbType.String, drDatos.Item(199).ToString())
    'db.AddInParameter(dbCommand, "@p_ValorMinimoSubasta", DbType.String, drDatos.Item(200).ToString())
    'db.AddInParameter(dbCommand, "@p_Decreto", DbType.String, drDatos.Item(201).ToString())
    'db.AddInParameter(dbCommand, "@p_RellenoDatosMercadosPapeles", DbType.String, drDatos.Item(202).ToString())
    'db.AddInParameter(dbCommand, "@p_Accion", DbType.String, drDatos.Item(203).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaSuspension", DbType.String, drDatos.Item(204).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaPosturaMercado", DbType.String, drDatos.Item(205).ToString())
    'db.AddInParameter(dbCommand, "@p_EscalaPrecio", DbType.String, drDatos.Item(206).ToString())
    'db.AddInParameter(dbCommand, "@p_PicturePrecio", DbType.String, drDatos.Item(207).ToString())
    'db.AddInParameter(dbCommand, "@p_PicturePrecioFinal", DbType.String, drDatos.Item(208).ToString())
    'db.AddInParameter(dbCommand, "@p_DivisorPrecio", DbType.String, drDatos.Item(209).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaDerechos", DbType.String, drDatos.Item(210).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaPosturasEnCombinada", DbType.String, drDatos.Item(211).ToString())
    'db.AddInParameter(dbCommand, "@p_RellenoDatosMercadosAcciones", DbType.String, drDatos.Item(212).ToString())
    'db.AddInParameter(dbCommand, "@p_TasaDolares", DbType.String, drDatos.Item(213).ToString())
    'db.AddInParameter(dbCommand, "@p_TasaMonedaLocal", DbType.String, drDatos.Item(214).ToString())
    'db.AddInParameter(dbCommand, "@p_TasaLibor", DbType.String, drDatos.Item(215).ToString())
    'db.AddInParameter(dbCommand, "@p_TasaSpread", DbType.String, drDatos.Item(216).ToString())
    'db.AddInParameter(dbCommand, "@p_Billetes1Dolar", DbType.String, drDatos.Item(217).ToString())
    'db.AddInParameter(dbCommand, "@p_Billetes5Dolares", DbType.String, drDatos.Item(218).ToString())
    'db.AddInParameter(dbCommand, "@p_Billetes10Dolares", DbType.String, drDatos.Item(219).ToString())
    'db.AddInParameter(dbCommand, "@p_Billetes20Dolares", DbType.String, drDatos.Item(220).ToString())
    'db.AddInParameter(dbCommand, "@p_Billetes50Dolares", DbType.String, drDatos.Item(221).ToString())
    'db.AddInParameter(dbCommand, "@p_Billetes100Dolares", DbType.String, drDatos.Item(222).ToString())
    'db.AddInParameter(dbCommand, "@p_Billetes2Dolar", DbType.String, drDatos.Item(223).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaEntregaBilletes", DbType.String, drDatos.Item(224).ToString())
    'db.AddInParameter(dbCommand, "@p_NumeroRueda", DbType.String, drDatos.Item(225).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoInstitDirectorRueda", DbType.String, drDatos.Item(226).ToString())
    'db.AddInParameter(dbCommand, "@p_HoraCierreSubasta", DbType.String, drDatos.Item(227).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaFormaRueda", DbType.String, drDatos.Item(228).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaTasa", DbType.String, drDatos.Item(229).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaAdjudicacion", DbType.String, drDatos.Item(230).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaCuantaTransferencia", DbType.String, drDatos.Item(231).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaConfirmadoDirector", DbType.String, drDatos.Item(232).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaRetiroCustodia", DbType.String, drDatos.Item(233).ToString())
    'db.AddInParameter(dbCommand, "@p_OrigenPostura", DbType.String, drDatos.Item(234).ToString())
    'db.AddInParameter(dbCommand, "@p_Precio2", DbType.String, drDatos.Item(235).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaPlazo", DbType.String, drDatos.Item(236).ToString())
    'db.AddInParameter(dbCommand, "@p_RellenoDatosRueda", DbType.String, drDatos.Item(237).ToString())
    'db.AddInParameter(dbCommand, "@p_RendimientoAsignado", DbType.String, drDatos.Item(238).ToString())
    'db.AddInParameter(dbCommand, "@p_NumeroPedido", DbType.String, drDatos.Item(239).ToString())
    'db.AddInParameter(dbCommand, "@p_NumeroAsignado", DbType.String, drDatos.Item(240).ToString())
    'db.AddInParameter(dbCommand, "@p_PrecioAsignado", DbType.String, drDatos.Item(241).ToString())
    'db.AddInParameter(dbCommand, "@p_MontoEfectivoAsignado", DbType.String, drDatos.Item(242).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaODAsignacion", DbType.String, drDatos.Item(243).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoPosturaAceptacion", DbType.String, drDatos.Item(244).ToString())
    'db.AddInParameter(dbCommand, "@p_NumeroLiquidacion", DbType.String, drDatos.Item(245).ToString())
    'db.AddInParameter(dbCommand, "@p_HoraExpiracion", DbType.String, drDatos.Item(246).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaRevisarCalce", DbType.String, drDatos.Item(247).ToString())
    'db.AddInParameter(dbCommand, "@p_RellenoDatosAdicionales", DbType.String, drDatos.Item(248).ToString())
    'db.AddInParameter(dbCommand, "@p_PrecioSpot", DbType.String, drDatos.Item(249).ToString())
    'db.AddInParameter(dbCommand, "@p_PrecioFinal", DbType.String, drDatos.Item(250).ToString())
    'db.AddInParameter(dbCommand, "@p_Iva", DbType.String, drDatos.Item(251).ToString())
    'db.AddInParameter(dbCommand, "@p_PuntosFw", DbType.String, drDatos.Item(252).ToString())
    'db.AddInParameter(dbCommand, "@p_MarcaPrecio", DbType.String, drDatos.Item(253).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaTransaccionParaPostulantes", DbType.String, drDatos.Item(254).ToString())
    'db.AddInParameter(dbCommand, "@p_McodTransaccion", DbType.String, drDatos.Item(255).ToString())
    'db.AddInParameter(dbCommand, "@p_Contador", DbType.String, drDatos.Item(256).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderasTransaccion", DbType.String, drDatos.Item(257).ToString())
    'db.AddInParameter(dbCommand, "@p_RellenoDatosAdicionalesTransaccion", DbType.String, drDatos.Item(258).ToString())
    'db.AddInParameter(dbCommand, "@p_UsuarioPostura1", DbType.String, drDatos.Item(259).ToString())
    'db.AddInParameter(dbCommand, "@p_McodPostura1", DbType.String, drDatos.Item(260).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoInstitucionPostura1", DbType.String, drDatos.Item(261).ToString())
    'db.AddInParameter(dbCommand, "@p_Ciudad3cPostura1", DbType.String, drDatos.Item(262).ToString())
    'db.AddInParameter(dbCommand, "@p_AgenciaPostura1", DbType.String, drDatos.Item(263).ToString())
    'db.AddInParameter(dbCommand, "@p_Sucursal4cPostura1", DbType.String, drDatos.Item(264).ToString())
    'db.AddInParameter(dbCommand, "@p_CiudadPostura1", DbType.String, drDatos.Item(265).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoInstitucionBancoPostura1", DbType.String, drDatos.Item(266).ToString())
    'db.AddInParameter(dbCommand, "@p_Ciudad3cBancoPostura1", DbType.String, drDatos.Item(267).ToString())
    'db.AddInParameter(dbCommand, "@p_AgenciaBancoPostura1", DbType.String, drDatos.Item(268).ToString())
    'db.AddInParameter(dbCommand, "@p_Sucursal4cBancoPostura1", DbType.String, drDatos.Item(269).ToString())
    'db.AddInParameter(dbCommand, "@p_CiudadBancoPostura1", DbType.String, drDatos.Item(270).ToString())
    'db.AddInParameter(dbCommand, "@p_UsuarioBanco1", DbType.String, drDatos.Item(271).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaClienteEtcPostura1", DbType.String, drDatos.Item(272).ToString())
    'db.AddInParameter(dbCommand, "@p_TotalPostura1", DbType.String, drDatos.Item(273).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaAceptacion", DbType.String, drDatos.Item(274).ToString())
    'db.AddInParameter(dbCommand, "@p_HoraAceptacion", DbType.String, drDatos.Item(275).ToString())

    'db.AddInParameter(dbCommand, "@p_Ciudad3cIntermediaria", DbType.String, drDatos.Item(277).ToString())
    'db.AddInParameter(dbCommand, "@p_AgenciaIntermediaria", DbType.String, drDatos.Item(278).ToString())
    'db.AddInParameter(dbCommand, "@p_Sucursal4cIntermediaria", DbType.String, drDatos.Item(279).ToString())
    'db.AddInParameter(dbCommand, "@p_CiudadIntermediaria", DbType.String, drDatos.Item(280).ToString())
    'db.AddInParameter(dbCommand, "@p_UsuarioSucursalIntermediario", DbType.String, drDatos.Item(281).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoInstitucionIntermediaria1", DbType.String, drDatos.Item(282).ToString())
    'db.AddInParameter(dbCommand, "@p_Ciudad3cIntermediaria1", DbType.String, drDatos.Item(283).ToString())
    'db.AddInParameter(dbCommand, "@p_AgenciaIntermediaria1", DbType.String, drDatos.Item(284).ToString())
    'db.AddInParameter(dbCommand, "@p_Sucursal4cIntermediaria1", DbType.String, drDatos.Item(285).ToString())
    'db.AddInParameter(dbCommand, "@p_CiudadIntermediaria1", DbType.String, drDatos.Item(286).ToString())
    'db.AddInParameter(dbCommand, "@p_UsuarioSucursalIntermediario1", DbType.String, drDatos.Item(287).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaBrokerageComprador", DbType.String, drDatos.Item(288).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaBrokerageVendedor", DbType.String, drDatos.Item(289).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaViaIntermediarioComprador", DbType.String, drDatos.Item(290).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaViaIntermediarioVendedor", DbType.String, drDatos.Item(291).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoPrimaryuserPostura1", DbType.String, drDatos.Item(292).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaRegistraConOtr", DbType.String, drDatos.Item(293).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaOnOffScreen", DbType.String, drDatos.Item(294).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaCambianCamposAdicionales", DbType.String, drDatos.Item(295).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaAceptacionPendiente", DbType.String, drDatos.Item(296).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaProcedencia", DbType.String, drDatos.Item(297).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaModificadorPrioridad", DbType.String, drDatos.Item(298).ToString())
    'db.AddInParameter(dbCommand, "@p_ComisionPostura1", DbType.String, drDatos.Item(299).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaComision1", DbType.String, drDatos.Item(300).ToString())
    'db.AddInParameter(dbCommand, "@p_ComisionBolsa1", DbType.String, drDatos.Item(301).ToString())
    'db.AddInParameter(dbCommand, "@p_CodigoEntidadPublica1", DbType.String, drDatos.Item(302).ToString())
    'db.AddInParameter(dbCommand, "@p_EntidadPublica3c1", DbType.String, drDatos.Item(303).ToString())
    'db.AddInParameter(dbCommand, "@p_RellenoDatosAceptacion1", DbType.String, drDatos.Item(304).ToString())
    'db.AddInParameter(dbCommand, "@p_IdentificadorLinkA", DbType.String, drDatos.Item(305).ToString())
    'db.AddInParameter(dbCommand, "@p_IdentificadorLinkB", DbType.String, drDatos.Item(306).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaBrokerPostura1", DbType.String, drDatos.Item(307).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaPrecioAceptado", DbType.String, drDatos.Item(308).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderasPostura1", DbType.String, drDatos.Item(309).ToString())
    'db.AddInParameter(dbCommand, "@p_RellenoDatosAceptacion", DbType.String, drDatos.Item(310).ToString())
    'db.AddInParameter(dbCommand, "@p_UsuarioSolicitante", DbType.String, drDatos.Item(311).ToString())
    'db.AddInParameter(dbCommand, "@p_HoraOriginal", DbType.String, drDatos.Item(312).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaRetiroParaModificar", DbType.String, drDatos.Item(313).ToString())
    'db.AddInParameter(dbCommand, "@p_BanderaHoraOriginal", DbType.String, drDatos.Item(314).ToString())
    'db.AddInParameter(dbCommand, "@p_RellenoDatosAnulacionModificacion", DbType.String, drDatos.Item(315).ToString())
#End Region

End Class
